services:
  database:
    container_name: db-mobile
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=mobile
    ports:
      - 5432:5432
    volumes:
      - ./structure:/docker-entrypoint-initdb.d
